            <div class="content__header">
                <h2>Gestion des réservations</h2>
            </div>
            <section>
                <table>
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Membre</th>
                            <th>Date réservation</th>
                            <th>Détails</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($reservation as $item): ?>
                        <tr>
                            <td><?= intval($item['Id']); ?></td>
                            <td><?= htmlspecialchars($item['FirstName']); ?> <?= htmlspecialchars($item['LastName']); ?></td>
                            <td><?= htmlspecialchars($item['Date']); ?></td>
                            <td>
                            <a href="reservation/details/<?= intval($item['Id']);?>">+</a>     
                        </tr>                       
                    <?php endforeach; ?> 
                    </tbody>
                </table>
            </section>