    <section class="dashboard">
    <div>
        <h2>dashboard</h2>
    </div>
        <div class="card">
            <div><?= intval($booking['Booking']); ?></div> 
            <p>réservations passées sur le site</p>
        </div>
        <div class="card">
            <div><?= intval($user['nb_user']); ?></div>
            <p>membres inscrits sur le site depuis le 01/01/2021</p>
        </div>
        <div class="card">
            <p>Yoga le plus réservé:</p>
            <div><?= htmlspecialchars($course['Name']); ?></div>
        </div>
    </section>