<!DOCTYPE html>
<html lang="en">
<?php 
require 'views/admin/inc_admin/head.phtml';
?>
<body>
    <div class="container admin ">
        <?php require 'views/admin/inc_admin/header.phtml'; ?>
        <main class="main__admin">
        <?php if (hasFlashes('error')): ?>
            <div class="alert error">
                <?php foreach (getFlashes('error') as $message): ?>
                <p><?=$message?></p>
                <?php endforeach?>            
            </div>
        <?php endif?>
        <?php if (hasFlashes('success')): ?>
            <div class="alert success">
                <?php foreach (getFlashes('success') as $message): ?>
                <p><?=$message?></p>
                <?php endforeach?>
            </div>
        <?php endif?>
            <?= $pageContent; ?>
        </main>
    </div>
    <script src="assets/js/main_admin.js"></script>
</body>
</html>