            <div class="content__header">
                <h2>Edition d'un enseignant</h2>
            </div>
            <form class="form" enctype="multipart/form-data" action="teacher/update/<?= intval($teacher['Id']); ?>" method="POST">
                <input type="hidden" name="picture" value="<?= $teacher['Picture']; ?>">
                <fieldset>
                    <legend>Identité</legend>
                    <div class="field">
                        <label for="lastName">Nom</label>
                        <input name="lastName" type="text" required aria-required="true" value="<?= htmlspecialchars($teacher['LastName']); ?>">
                    </div>
                    <div class="field">
                        <label for="firstName">Prénom</label>
                        <input name="firstName" type="text" required aria-required="true" value="<?= htmlspecialchars($teacher['FirstName']); ?>">
                    </div>
                    <div class="field">
                        <label for="email">Email</label>
                        <input name="email" type="email" required aria-required="true" value="<?= htmlspecialchars($teacher['Email']); ?>">
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Coordonnées</legend>
                    <div class="field">
                        <label for="address">Adresse</label>
                        <input name="address" type="text" required aria-required="true" value="<?= htmlspecialchars($teacher['Address1']); ?>">
                    </div>
                    <div class="field">  
                        <label for="address2">Complément d'adresse</label>
                        <input name="address2" type="text" value="<?= htmlspecialchars($teacher['Address2']); ?>"> 
                    </div> 
                    <div class="field">
                        <label for="zipcode">Code postal</label>
                        <input name="zipcode" type="text" required aria-required="true" value="<?= htmlspecialchars($teacher['ZipCode']); ?>">
                    </div>
                    <div class="field">
                        <label for="city">Ville</label>
                        <input name="city" type="text" required aria-required="true" value="<?= htmlspecialchars($teacher['City']); ?>">
                    </div>
                    <div class="field">
                        <label for="phone">Téléphone</label>
                        <input name="phone" type="text" required aria-required="true" value="<?= htmlspecialchars($teacher['Phone']); ?>">
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Photo</legend>
                    <div class="field">
                        <input type="file" id="photo_teacher" name="photo_teacher">
                        <label for="photo_teacher" data-browse="Parcourir"></label>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Biographie</legend>
                    <div class="field">
                        <label for="bio"></label>
                        <textarea name="bio" id="bio" cols="30" rows="10" required aria-required="true"><?= htmlspecialchars($teacher['Description']); ?>"</textarea>
                    </div>
                </fieldset>
                <button class="btn" type="submit">Valider</button>
                <a href="teacher" class="btn">Retour</a>
            </form>