            <div class="content__header">
                <h2>Gestion des enseignants</h2>
                <a class="btn" href="teacher/create">Créer</a>
            </div>
            <section>
                <h3>Enseignants</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Prénom</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($teachers as $teacher): ?>
                        <tr>
                            <td><?= htmlspecialchars($teacher['LastName']); ?></td>
                            <td><?= htmlspecialchars($teacher['FirstName']); ?></td>
                            <td>
                                <a class="icon icon--modify" href="teacher/update/<?= intval($teacher['Id']); ?>"><i class="fas fa-edit"></i></a>
                                <a class="icon icon--modify" href="teacher/deleteTeacher/<?= intval($teacher['Id']); ?>"><i class="far fa-trash-alt"></i></a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </section>