
<section>
    <h2>Erreur 404</h2>
<p>Une erreur est survenue, merci de vous reconnecter plus tard ou de contacter un administrateur.</p>

<h3>Détails de l'erreur</h3>
<p>N'hésitez pas à fournir le code d'erreur et le message suivant à l'administrateur :</p>
<p><strong>Code : </strong> <?= $code;?></p>
<p><strong>Message : </strong><em><?= $message;?></em></p>

<a href="home">Retour à l'accueil du site</a>
</section>