            <section>
                <h2>Connexion</h2>
                <form class="form" action="user/login" method="POST">
                    <fieldset>
                        <div class="field">
                            <label for="email">Email</label>
                            <input name="email" type="email" required aria-required="true">
                        </div>
                        <div class="field">
                            <label for="password">Mot de passe</label>
                            <input name="password" type="password" required aria-required="true">
                        </div>
                        <div>
                        <button type="submit" class="btn">Se connecter</button>
                        </div>
                    </fieldset>
                </form>
                <div> Pas encore de compte ? C'est le moment de vous inscrire : <a href="user/register">ici !</a>
            </section>