            <section>
                <h2>Mon compte</h2>
                <div>
                    <h3>Mes informations</h3>
                    <div>
                        <p><?= $_SESSION['user']['FirstName']; ?> <?= $_SESSION['user']['LastName']; ?></p>
                        <p><?= $userInfos['Address1']; ?></p>
                        <?php if(isset($userInfos['Address2'])): ?>
                        <p><?= $userInfos['Address2']; ?></p>
                        <?php endif; ?>
                        <p><?= $userInfos['ZipCode']; ?></p>
                        <p><?= $userInfos['City']; ?></p>
                        <p><?= $_SESSION['user']['Email']; ?></p>
                        <a href="user/update/<?= intval($_SESSION['user']['Id']);?>" class="btn">Modifier mes infos</a>
                    </div>
                </div>
                <div>
                <?php if(!$userBooking): ?>
                    <h3>Réservations</h3>
                        <p>Vous n'avez fait aucune réservation!</p>
                    <?php endif; ?>
                <?php if($userBooking): ?>
                    <?php foreach($bookingDetails as $item): ?>   
                        <table>
                            <thead>
                                <th>N°Resa</th>
                                <th>Cours</th>
                                <th>Date</th>
                                <th>Horaire</th>
                                <th>Prix</th>
                            </thead>
                            <tbody>                  
                                <tr>
                                    <td><?= intval($item['Reservation_Id']); ?> </td>
                                    <td><?= htmlspecialchars($item['Name']); ?></td>
                                    <td><?= htmlspecialchars($item['Date']); ?></td>
                                    <td><?= htmlspecialchars($item['Time']); ?></td>
                                    <td><?= intval($item['Price']); ?> €</td>
                                </tr>
                            <tbody>
                        </table>                
                    <?php endforeach; ?>
                    <p>Si vous souhaitez annuler une réservation, envoyez-nous un email à yogastudio@gmail.com</p>
                    <?php endif ;?>           
                </div>
            </section>