            <section>
                <h2>L'équipe du Yoga Studio</h2>
                <?php foreach($teachers as $item): ?>
                <article class="team__element team--description">
                    <div>
                        <img src="uploads/<?= $item['Picture'];?>" alt="photo de <?= htmlspecialchars($item['FirstName']).' '.htmlspecialchars($item['LastName']); ?>">
                    </div>
                    <h3><?= htmlspecialchars($item['FirstName']).' '.htmlspecialchars($item['LastName']); ?></h3>
                    <p><?= $item['Description']; ?></p>
                </article>
                <?php endforeach; ?>
            </section>