            <section class="courses__details">
                <h2>Les cours</h2>
                <?php foreach($courses as $item): ?>
                <article>
                    <h3><?= htmlspecialchars($item['Name']); ?></h3>
                    <p><?= htmlspecialchars($item["Long_description"]); ?></p>
                </article>
                <?php endforeach; ?>
                <div>
                    <h2>Envie de découvrir ?</h2> 
                    <p>Alors réservez-vite votre cours </p>
                    <a href="timetable" class="btn">Ici</a>
                </div>
            </section>