            <div class="content__header">
                <h2>Edition d'un type de yoga</h2>
            </div>
            <form action=course/update/<?=intval($course['Id']); ?> method="POST">
                <fieldset>
                    <div class="field">
                        <div class="field">
                            <label for="name">Nom</label>
                            <input name="name" type="text" required aria-required="true" value="<?= htmlspecialchars($course['Name']); ?>">
                        </div>
                </fieldset>
                <fieldset>
                    <legend>Description</legend>
                    <div>
                        <label for="shortDescription">Description courte (page d'accueil)</label>
                        <textarea name="shortDescription" id="shortDescription" cols="30" rows="2" required aria-required="true" ><?= htmlspecialchars($course["Short_description"]); ?></textarea>
                    </div>
                    <div>
                        <label for="description">Description longue</label>
                        <textarea name="description" id="description" cols="30" rows="10" required aria-required="true"><?= htmlspecialchars($course["Long_Description"]); ?></textarea>
                    </div>
                </fieldset>
                <div class="field">
                    <button  type="submit" class="btn">Valider</button>
                    <a href="course" class="btn">Retour</a>
                </div> 
            </form>