            <div class="content__header">
                <h2>Edition d'une séance</h2>
            </div>
            <form class="form" action="yogaclass/update/<?=intval($data['Id']); ?>" method="POST">
                <fieldset>
                    <div class="field">
                        <label for="yogaType">Type Yoga</label>
                        <select name="yogaType" id="yogaType" required aria-required="true">
                            <option selected="selected" disabled value="<?= intval($data['Id']); ?>"><?= htmlspecialchars($data['Name']); ?></option>
                            <?php foreach($courses as $item): ?>
                            <option value="<?= intval($item['Id']); ?>"><?= htmlspecialchars($item['Name']); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="field">
                        <label for="teacher">Enseignants</label>
                        <select name="teacher" id="teacher" required aria-required="true"d>
                            <option selected="selected" disabled value="<?= intval($data['Id']); ?>"><?= htmlspecialchars($data['FirstName']).' '.htmlspecialchars($data['LastName']); ?></option>
                            <?php foreach($teachers as $item): ?>
                            <option value="<?= intval($item['Id']); ?>"><?= htmlspecialchars($item['FirstName']).' '.htmlspecialchars($item['LastName']); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="field">
                        <label for="date">Date</label>
                        <input name="date" type="date" value="<?= htmlspecialchars($data['Date']); ?>" required aria-required="true">
                    </div>
                    <div class="field">
                        <label for="time">Heure</label>
                        <input name="time" type="time" value="<?= htmlspecialchars($data['Time']); ?>" required aria-required="true">
                    </div>
                    <div class="field">
                        <label for="seat">Places</label>
                        <input name="seat" type="number" min="1" value="<?= htmlspecialchars($data['Number_participants']); ?>" required aria-required="true">
                    </div>
                    <div class="field">
                        <label for="price">Prix</label>
                        <input name="price" type="number" min="1" max="50" value="<?= htmlspecialchars($data['Price']); ?>"required aria-required="true">
                    </div>
                </fieldset>
                <button class="btn" type="submit">Valider</button>
                <a href="yogaclass" class="btn">Retour</a> 
            </form>