            <div class="content__header">
                <h2>Gestion des séances</h2>
                <a class="btn--create" href="yogaclass/create">Créer</a>
            </div>
            <section>
                <h3>Séances planifiées</h3>
                <table class="table--responsive">
                    <thead>
                        <tr>
                            <th>Type Yoga</th>
                            <th>Enseignant</th>
                            <th>Date</th>
                            <th>Heure</th>
                            <th>Modifier</th>
                            <th>Supprimer</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($yogaclass as $item): ?>
                    <tr>
                        <td data-label="Type Yoga"><?= htmlspecialchars($item['Name']); ?></td>
                        <td data-label="Enseignant"><?= htmlspecialchars($item['FirstName']); ?></td>
                        <td data-label="Date"><?= htmlspecialchars($item['Date']); ?></td>
                        <td data-label="Heure"><?= htmlspecialchars($item['Time']); ?></td>
                        <td data-label="Modifier" class=""><a class="btn--edit" href=yogaclass/update/<?= intval($item['Id']); ?>><i class="fas fa-edit"></i></a></td>
                        <td data-label="Supprimer" ><a class="btn--delete" href=yogaclass/deleteClass/<?= intval($item['Id']); ?>><i class="far fa-trash-alt"></i></a></td>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </section>