            <div class="content__header">
                <h2>Gestion des séances</h2>
                <a class="btn" href="yogaclass/create">Créer</a>
            </div>
            <section>
                <h3>Séances planifiées</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Type Yoga</th>
                            <th>Enseignant</th>
                            <th>Date</th>
                            <th>Heure</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($yogaclass as $item): ?>
                    <tr>
                        <td><?= htmlspecialchars($item['Name']); ?></td>
                        <td><?= htmlspecialchars($item['FirstName']); ?></td>
                        <td><?= htmlspecialchars($item['Date']); ?></td>
                        <td><?= htmlspecialchars($item['Time']); ?></td>
                        <td>
                            <a class="btn--edit" href=yogaclass/update/<?= intval($item['Id']); ?>><i class="fas fa-edit"></i></a>
                            <a class="btn--delete" href=yogaclass/deleteClass/<?= intval($item['Id']); ?>><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </section>