            <div class="content__header">
                <h2>Création d'une séance</h2>
            </div>
                <form class="form" action="yogaclass/create" method="POST">
                    <fieldset>
                        <div class="field">
                            <label for="yogaType">Type Yoga</label>
                            <select name="yogaType" id="yogaType" aria-required="true">
                                <?php foreach($courses as $item): ?>
                                <option value="<?= intval($item['Id']); ?>"><?= htmlspecialchars($item['Name']); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="field">
                            <label for="teacher">Enseignants</label>
                            <select name="teacher" id="teacher" aria-required="true">
                                <?php foreach($teachers as $item): ?>
                                <option value="<?= intval($item['Id']); ?>"><?= htmlspecialchars($item['FirstName']).' '.htmlspecialchars($item['LastName']); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="field">
                            <label for="date">Date</label>
                            <input name="date" id="date" type="date" required>
                        </div>
                        <div class="field">
                            <label for="time">Heure</label>
                            <input name="time" id="time" type="time" required>
                        </div>
                        <div class="field">
                            <label for="seat">Places</label>
                            <input name="seat" id="seat" type="number" min="1" aria-required="true">
                        </div>
                        <div class="field">
                            <label for="price">Prix</label>
                            <input name="price" id="price" type="number" min="1" max="50" aria-required="true">
                        </div>
                    </fieldset>
                    <button class="btn" type="submit">Créer</button>
                    <a href="yogaclass" class="btn">Retour</a>
                </form>
    